export const API = {
    
    Login: 'connect/token',
    validateUser:'/UserLogin',
    resetPassword: 'api/user/',
    getShops:'shop/',
    getShopdbyLocation:'shop/GetShopsByLocation',
    getCategories:'ProductCategory/',
    getSubCategories:'subcategory/',
    getProducts:'Product/',
    getProductsbySubcategory:'ShopProducts/GetShopProductsBySubCategory',
    getShopAds:'ShopAds/',
    postOrder:'ShopOrder/CreateOrder',
    getLookup:'LookUp/',
    generateOtp:'otp/GenerateOtp',
    verifyOtp:'otp/VerifyOTP',
    sendOrderSMS:'otp/SendPikatooSMS',
    updateProfile:'otp/UpdateProfile',
    getProfile:'otp/UserProfile',
    getShopSubcategory:'ShopSubCategory',
    putShop:'Shop',
    getShop:'Shop/getShopMaster/',
    putLocation:'Location',
    getLocation:'Location',
    saveShopProfilePic:'ShopGallery',
    getShopOrderDetails:'ShopOrder/OrderDetails',
    getShopProductsBysearch:'ShopProducts/GetShopProductsBySearch',
    putShopProducts:'ShopProducts',
    GetAllShopProducts:'ShopProducts/GetAllShopProducts',
    putBulkShopProducts:'ShopProducts/AddMultiShopProducts',
    placeOrder:"Sales/CreateOrder",
    getOrders:'Sales/Orders',
    getOrderDetails:'Sales/OrderDetails',
    getOrderStatus:'Sales/OrderStatus',
    updateOrderStatus:'Sales/CreateOrderStatus',
    addproduct:"Product"

}